version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
  cypress: cypress-io/cypress@1.20.0
jobs:
  server_test:
    docker:
      - image: circleci/node:9.9.0

    working_directory: ~/repo/server

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - codecov/upload:
          file: coverage/coverage-final.json
          token: '${CODECOV_TOKEN}'

workflows:
  version: 2
  complete_test:
    jobs:
      - server_test
      - cypress/install:
          working_directory: ~/repo/client
      - cypress/run:
          yarn: true
          working_directory: ~/repo/client
          filters:
            branches:
              only: 
                - master

