version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
  cypress: cypress-io/cypress@1.20.0
jobs:
  server_test:
    docker:
      - image: circleci/node:9.9.0

    working_directory: ~/repo/server

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - ~/.cache
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - codecov/upload:
          file: coverage/coverage-final.json
          token: '${CODECOV_TOKEN}'

workflows:
  version: 2
  server:
    jobs:
      - server_test
      - cypress/run:
          yarn: true
          install-command: yarn install
          post-checkout:
            - run: cd server && npm install
            - run: killall -9 node
          command: yarn run test:e2e
          working_directory: client
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "client/package.json" }}
          requires:
            - server_test
          

