version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:9.9.0

    working_directory: ~/repo/server

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run:
          command: npm test
          no_output_timeout: "30s"
      - codecov/upload:
          file: coverage/coverage-final.json
          token: '${CODECOV_TOKEN}'
